#ifndef ELF_MYEMULATOR2_H
#define ELF_MYEMULATOR2_H

#define EM_MYEMULATOR2 0xF2E2

#include "elf/reloc-macros.h"

START_RELOC_NUMBERS (elf_myemulator2_reloc_type)
  RELOC_NUMBER (R_MYEMULATOR2_NONE, 0)
  RELOC_NUMBER (R_MYEMULATOR2_32, 1)
  RELOC_NUMBER (R_MYEMULATOR2_BRANCH13, 2)
  RELOC_NUMBER (R_MYEMULATOR2_JUMP26, 3)
  RELOC_NUMBER (R_MYEMULATOR2_HI20, 4)
  RELOC_NUMBER (R_MYEMULATOR2_LO12, 5)
END_RELOC_NUMBERS (R_MYEMULATOR2_max)

#endif
