# SPDX-License-Identifier: GPL-2.0
obj-y += head.o
obj-y += setup.o
obj-y += traps.o
obj-y += process.o
obj-y += time.o
obj-y += irq.o
obj-y += syscall.o
obj-y += entry.o
obj-y += ptrace.o

extra-y := vmlinux.lds
