# SPDX-License-Identifier: GPL-2.0
obj-y += head.o
obj-y += console.o
obj-y += serial.o
obj-y += setup.o
obj-y += traps.o
obj-y += process.o
obj-y += switch.o
obj-y += time.o
obj-y += vmalloc_test.o
obj-y += irq.o
obj-y += syscall.o
obj-y += entry.o
obj-y += ptrace.o
obj-$(CONFIG_MYEMU2_BLOCK) += block.o

extra-y := vmlinux.lds
